### ISSUE TITLE
Extend documentation

### ISSUE THREAD

**Issue by Shimmi** [Shimmi/docker-jenkins#1]
**ToDo**
- [x] README with basic overview and description
- [ ] Add security notice on shared `docker.sock`
- [ ] Jenkins set-up (quick) guide
- [ ] Example on creating Declarative pipeline job
- [ ] TBD ...
